<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE model [
        <!ELEMENT model (palette|colorkeys|spritemap|layers|logic)*>
        <!ATTLIST model
                name CDATA #REQUIRED
                dir CDATA #REQUIRED
                width CDATA #REQUIRED
                height CDATA #REQUIRED
                scale CDATA #REQUIRED
                originX CDATA #IMPLIED
                originY CDATA #IMPLIED>
        <!ELEMENT palette (common|property)*>
        <!ELEMENT common (color)*>
        <!ELEMENT color (#PCDATA)>
        <!ATTLIST color
                name CDATA #REQUIRED>
        <!ELEMENT property (color)*>
        <!ATTLIST property
                default CDATA #REQUIRED
                name CDATA #REQUIRED
                src CDATA #REQUIRED>
        <!ELEMENT colorkeys (key)*>
        <!ELEMENT key (#PCDATA)>
        <!ATTLIST key
                base CDATA #REQUIRED
                src CDATA #REQUIRED
                transform CDATA #IMPLIED>
        <!ELEMENT spritemap (cell)*>
        <!ATTLIST spritemap
                file CDATA #REQUIRED>
        <!ELEMENT cell (#PCDATA)>
        <!ATTLIST cell
                dx CDATA #IMPLIED
                dy CDATA #IMPLIED
                name CDATA #REQUIRED
                rect CDATA #REQUIRED>
        <!ELEMENT layers (layer)*>
        <!ELEMENT layer (#PCDATA)>
        <!ATTLIST layer
                name CDATA #REQUIRED>
        <!ELEMENT logic (show|switch|if|hide|set)*>
        <!ELEMENT switch (case|default)*>
        <!ATTLIST switch
                value CDATA #IMPLIED>
        <!ELEMENT case (show|switch|if|hide|set)*>
        <!ATTLIST case
                test CDATA #IMPLIED
                value CDATA #IMPLIED
                values CDATA #IMPLIED>
        <!ELEMENT show (#PCDATA)>
        <!ATTLIST show
                part CDATA #REQUIRED>
        <!ELEMENT default (show|switch|if|hide|set)*>
        <!ELEMENT if (show|switch|if|hide|set|else)*>
        <!ATTLIST if
                test CDATA #REQUIRED>
        <!ELEMENT else (show|switch|if|hide|set)*>
        <!ELEMENT hide (#PCDATA)>
        <!ATTLIST hide
                part CDATA #REQUIRED>
        <!ELEMENT set (#PCDATA)>
        <!ATTLIST set
                var CDATA #REQUIRED
                value CDATA #IMPLIED>
        ]>
<!--suppress EqualityComparisonWithCoercionJS, CheckTagEmptyBody -->
    <model name="demo" dir="./res/charview/" width="200" height="220" scale="2" originX="15" originY="10">
    <palette>
        <!--Colors common for skin/hair/fur/scales/... go here. Can be overriden later-->
            <common>
            <color name="albino">#f2f2e8</color>
            <color name="aqua">#00cccc</color>
            <color name="ashen">#817d79</color>
            <color name="ashen2">#9f948e</color>
            <color name="auburn">#732d26</color>
            <color name="black">#333333</color>
            <color name="blond">#e0c685</color>
            <color name="blonde">#f2e4bf</color>
            <color name="blue">#405fce</color>
            <color name="bright pink">#f000f0</color>
            <color name="bronzed">#a89148</color>
            <color name="brown">#664400</color>
            <color name="caramel">#c39350</color>
            <color name="caramel2">#c38c50</color>
            <color name="cerulean">#59cfde</color>
            <color name="cerulean2">#377bc3</color>
            <color name="chocolate">#4a3b2b</color>
            <color name="crimson">#dc143c</color>
            <color name="crystal">#bc81ca</color>
            <color name="dark">#694e44</color>
            <color name="dark2">#352722</color>
            <color name="dusky">#f000f0</color>
            <color name="ebony">#3d3529</color>
			<color name="eldritch green">#87d981</color>
            <color name="emerald">#4cc875</color>
            <color name="fair">#edccbf</color>
            <color name="golden">#ffdd00</color>
            <color name="gray">#808080</color>
            <color name="green">#08a108</color>
            <color name="indigo">#4d0080</color>
            <color name="light">#feebd7</color>
            <color name="neon blue">#29eaff</color>
            <color name="spectral blue">#29eaff</color>
            <color name="glacial blue">#94f6ff</color>
            <color name="mahogany">#81473b</color>
            <color name="mahogany2">#672828</color>
            <color name="metallic">#9c9c9c</color>
            <color name="midnight">#30354a</color>
            <color name="olive">#ddad72</color>
            <color name="orange">#ffa600</color>
            <color name="peach">#f4c0a4</color>
            <color name="pink">#ffb3b3</color>
            <color name="purple">#7a007a</color>
            <color name="purplish black">#391939</color>
            <color name="red">#f02c0a</color>
            <color name="red2">#ff0000</color>
            <color name="russet">#aa6546</color>
            <color name="russet2">#793939</color>
            <color name="sable">#d6caa9</color>
            <color name="sanguine">#c03030</color>
            <color name="silky">#ffd6ff</color>
            <color name="silver">#d8e0e9</color>
            <color name="tan">#a3845c</color>
            <color name="tan2">#cfaa30</color>
            <color name="tawny">#b97f27</color>
            <color name="turquoise">#1ed9dc</color>
            <color name="white">#e6e6eb</color>
            <color name="yellow">#fff70f</color>
            <color name="aphotic blue-black">#08155e</color>
			<color name="bluish black">#22263a</color>
            <color name="ashen grayish-blue">#93b6c8</color>
            <color name="creamy-white">#f2ebde</color>
            <color name="crimson platinum">#d56c6c</color>
            <color name="blood-red">#d56c6c</color>
            <color name="blazing red">#ff6224</color>
            <color name="dark blue">#3d529e</color>
            <color name="dark gray">#534f59</color>
            <color name="dark green">#36582d</color>
            <color name="deep blue">#1e3667</color>
            <color name="deep red">#742525</color>
            <color name="ember">#ff6224</color>
            <color name="ghostly pale">#e3deed</color>
            <color name="glacial white">#dee5f2</color>
            <color name="golden blonde">#f5d88a</color>
            <color name="grayish-blue">#3f3f50</color>
            <color name="iridescent gray">#999999</color>
            <color name="leaf green">#5eba5e</color>
            <color name="light blonde">#ffe78f</color>
            <color name="light blue">#b1c8ec</color>
            <color name="light gray">#dddadd</color>
            <color name="light green">#c5eec3</color>
            <color name="light gray">#c4d1d9</color>
            <color name="light purple">#e4cdf3</color>
			<color name="light pink">#ffbdcb</color>
            <color name="lime green">#73df72</color>
			<color name="magenta">#470036</color>
            <color name="mediterranean-toned">#ac7339</color>
            <color name="metallic golden">#ddc469</color>
            <color name="metallic silver">#cfedfc</color>
            <color name="midnight black">#171622</color>
			<color name="midnight purple">#47314b</color>
            <color name="milky white">#f4dfdc</color>
            <color name="pale white">#fff4eb</color>
            <color name="pale yellow">#eeecaa</color>
            <color name="platinum blonde">#f7f3e8</color>
            <color name="platinum crimson">#ff745c</color>
            <color name="platinum-blonde">#ffe5c7</color>
            <color name="purplish-black">#7d597a</color>
			<color name="purplish-pink">#bc81ca</color>
            <color name="dark purple">#a700bd</color>
			<color name="eldritch purple">#7a5f95</color>
            <color name="quartz white">#ffffff</color>
            <color name="pure white">#ffffff</color>
            <color name="reddish-orange">#df8453</color>
            <color name="rough gray">#525252</color>
            <color name="sandy blonde">#ebd69e</color>
            <color name="sandy brown">#a28d57</color>
            <color name="sandy-blonde">#e0cd9f</color>
            <color name="shiny black">#1c262c</color>
            <color name="silver blonde">#fcfaf8</color>
            <color name="silver-white">#eff3f6</color>
            <color name="snow white">#f9f9fa</color>
			<color name="stormy blue">#2f308d</color>
            <color name="ghastly white">#f9f9fa</color>
            <color name="yellowish-green">#e1eca7</color>
            <color name="black and yellow">#000000</color>
            <color name="abyssal black">#000000</color>
            <color name="white and black">#eff3f6</color>
        </common>
        <property name="hair" src="hairColor" default="#ffffff">
            <color name="red">#d85741</color>
            <color name="flaxen">#e1ba94</color>
            <color name="brown">#674f42</color>
            <color name="black">#334252</color>
            <color name="gray">#647a7d</color>
            <color name="white">#aeaba3</color>
            <color name="raven">#101728</color>
            <color name="snowy">#dddfe4</color>
        </property>
        <property name="hair2" src="hairColor" default="#ffffff">
        </property>
        <property name="fur" src="skin.coat.color" default="#ffffff">
        </property>
        <property name="fur2" src="skin.coat.color2" default="#ffffff">
        </property>
        <property name="scales" src="skin.coat.color" default="#ffffff">
        </property>
        <property name="scales2" src="skin.coat.color2" default="#ffffff">
        </property>
        <property name="chitin" src="skin.coat.color" default="#ffffff">
        </property>
        <property name="chitin2" src="skin.coat.color2" default="#ffffff">
        </property>
        <property name="skin" src="skinTone" default="#ffffff">
            <color name="pale">#f2e8e3</color>
        </property>
        <property name="skin2" src="skin.base.color2" default="#ffffff">
            <color name="pale">#f2e8e3</color>
        </property>
        <property name="iris" src="eyes.colour" default="#0000ff">
        </property>
    </palette>
    <colorkeys>
        <key src="#FF88FF" base="hair" transform="lighten(25)"/>
		<key src="#f934f9" base="hair" transform="lighten(10)"/>
        <key src="#CC00CC" base="hair"/>
        <key src="#880088" base="hair" transform="darken(25)"/>
        <key src="#440044" base="hair" transform="darken(50)"/>
        <key src="#FFFF88" base="hair2" transform="lighten(25)"/>
        <key src="#CCCC00" base="hair2"/>
        <key src="#999900" base="hair2" transform="darken(25)"/>
        <key src="#333300" base="hair2" transform="darken(50)"/>
        <key src="#88FF88" base="fur" transform="lighten(25)"/>
        <key src="#00CC00" base="fur"/>
		<key src="#00ac00" base="fur" transform="darken(15)"/>
        <key src="#009900" base="fur" transform="darken(25)"/>
        <key src="#003300" base="fur" transform="darken(50)"/>
        <key src="#AA88FF" base="fur2" transform="lighten(25)"/>
        <key src="#6633CC" base="fur2"/>
        <key src="#442288" base="fur2" transform="darken(25)"/>
        <key src="#220044" base="fur2" transform="darken(50)"/>
        <key src="#8888FF" base="scales" transform="lighten(25)"/>
		<key src="#5c5cfe" base="scales" transform="lighten(10)"/>
        <key src="#4444FF" base="scales"/>
        <key src="#0000CC" base="scales" transform="darken(25)"/>
        <key src="#000033" base="scales" transform="darken(50)"/>
        <key src="#AAFFAA" base="scales2" transform="lighten(25)"/>
        <key src="#66CC66" base="scales2"/>
        <key src="#448844" base="scales2" transform="darken(25)"/>
        <key src="#223322" base="scales2" transform="darken(50)"/>
        <key src="#88FFFF" base="chitin" transform="lighten(25)"/>
        <key src="#44CCFF" base="chitin"/>
		<key src="#42bbe9" base="chitin" transform="darken(15)"/>
        <key src="#0099CC" base="chitin" transform="darken(25)"/>
        <key src="#006666" base="chitin" transform="darken(50)"/>
        <key src="#AACCDD" base="chitin2" transform="lighten(25)"/>
        <key src="#77AACC" base="chitin2"/>
		<key src="#6294bc" base="chitin2" transform="darken(15)"/>
        <key src="#4477AA" base="chitin2" transform="darken(25)"/>
        <key src="#114477" base="chitin2" transform="darken(50)"/>
        <key src="#FFE9CC" base="skin" transform="lighten(25)"/>
        <key src="#FACE8D" base="skin"/>
		<key src="#e7be82" base="skin" transform="darken(8)"/>
        <key src="#BC9B6D" base="skin" transform="darken(25)"/>
        <key src="#7C6647" base="skin" transform="darken(50)"/>
        <key src="#1C0F0F" base="skin" transform="darken(75)"/>
        <key src="#FFCCCC" base="skin2" transform="lighten(25)"/>
        <key src="#FF9999" base="skin2"/>
		<key src="#eb8d8d" base="skin2" transform="darken(8)"/>
        <key src="#BB7777" base="skin2" transform="darken(25)"/>
        <key src="#884444" base="skin2" transform="darken(50)"/>
        <key src="#221111" base="skin2" transform="darken(75)"/>
		<key src="#FF0000" base="iris"/>
		<key src="#AA0000" base="iris" transform="darken(25)"/>
        <key src="#FBCAAE" base="skin" transform="darken(25);saturate(25);shiftTo(0,25,25)"/>
		<key src="#ECB596" base="skin" transform="darken(50);saturate(25);shiftTo(0,25,25)"/>
        <!--<key src="#FFFFFF" base="sclera"/>-->
        <!--<key src="#0026FF" base="iris"/>-->
    </colorkeys>
    <!--<spritesheet file="char1.png" cellwidth="192" cellheight="192">
        <row>name1,name2,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,breasts/Dfur,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
    </spritesheet>-->


	<!-- LOCATION IN SCREEN AREA -->
    <spritemap file="body.png">
        <cell rect="1,90,49,59" name="torso/human" dx="79" dy="64"/>
        <cell rect="51,90,49,59" name="torso/fur" dx="79" dy="64"/>
        <cell rect="101,90,49,59" name="torso/chitin" dx="79" dy="64"/>
        <cell rect="151,90,49,59" name="torso/bee" dx="79" dy="64"/>
        <cell rect="201,90,49,59" name="torso/orca" dx="79" dy="64"/>
        <cell rect="251,90,49,59" name="torso/pscales" dx="79" dy="64"/>
        <cell rect="301,90,49,59" name="torso/scales" dx="79" dy="64"/>
        <cell rect="351,90,49,59" name="torso/goo" dx="79" dy="64"/>
        <cell rect="601,90,49,59" name="torso/panda" dx="79" dy="64"/>
        <cell rect="1101,90,49,59" name="torso/dscales" dx="79" dy="64"/>
		<cell rect="1151,90,49,59" name="torso/shark" dx="79" dy="64"/>
        <cell rect="451,90,49,59" name="torso_pattern/Bstripe" dx="79" dy="64"/>
        <cell rect="501,90,49,59" name="torso_pattern/Blightning" dx="79" dy="64"/>
        <cell rect="551,90,49,59" name="torso_pattern/Btatoo" dx="79" dy="64"/>
        <cell rect="801,90,49,59" name="torso_pattern/Bvenom" dx="79" dy="64"/>
        <cell rect="951,90,49,59" name="breasts_pattern/BgazerTar" dx="79" dy="64"/>
        <cell rect="1001,90,49,59" name="torso_pattern/BwindScars" dx="79" dy="64"/>
        <cell rect="1051,90,49,59" name="torso_pattern/Bbioluminescence" dx="80" dy="61"/>
        <cell rect="101,1304,99,119" name="full_pattern/gnome" dx="53" dy="20"/>
        <cell rect="201,1304,99,119" name="full_pattern/undine" dx="56" dy="21"/>
        <cell rect="301,1304,99,119" name="full_patternUnder/undine" dx="56" dy="21"/>
        <cell rect="401,1304,99,119" name="full_pattern/sylph" dx="56" dy="59"/>
        <cell rect="1,150,49,59" name="arms_bg/human" dx="56" dy="64"/>
        <cell rect="51,150,49,59" name="arms_bg/fur" dx="56" dy="64"/>
        <cell rect="551,150,49,59" name="arms_bg/furracoon" dx="56" dy="64"/>
        <cell rect="101,150,49,59" name="arms_bg/chitin" dx="56" dy="64"/>
        <cell rect="151,150,49,59" name="arms_bg/bee" dx="56" dy="64"/>
        <cell rect="201,150,49,59" name="arms_bg/chitin2" dx="56" dy="64"/>
        <cell rect="251,150,49,59" name="arms_bg/orca" dx="56" dy="64"/>
        <cell rect="301,150,49,59" name="arms_bg/pscales" dx="56" dy="64"/>
        <cell rect="351,150,49,59" name="arms_bg/scales" dx="56" dy="64"/>
		<cell rect="351,150,49,59" name="arms_bg/dscales" dx="56" dy="64"/>
        <cell rect="1151,150,49,59" name="arms_bg/shark" dx="56" dy="64"/>
        <cell rect="401,150,49,59" name="arms_bg/goo" dx="56" dy="64"/>
        <cell rect="701,150,49,59" name="arms_bg/panda" dx="56" dy="64"/>
        <cell rect="801,150,49,59" name="arms_bg/demonlewd" dx="56" dy="64"/>
        <cell rect="1,853,49,59" name="arms_bg/displacerquad_human" dx="56" dy="56"/>
        <cell rect="51,853,49,59" name="arms_bg/displacerquad_fur" dx="56" dy="56"/>
        <cell rect="101,853,49,59" name="arms_bg/displacerquad_scales" dx="56" dy="56"/>
		<cell rect="101,853,49,59" name="arms_bg/displacerquad_dscales" dx="56" dy="56"/>
        <cell rect="151,853,49,59" name="arms_bg/displacerquad_pscales" dx="56" dy="56"/>
        <cell rect="201,853,49,59" name="arms_bg/displacerquad_chitin" dx="56" dy="56"/>
        <cell rect="251,853,49,59" name="arms_bg/displacerquad_orca" dx="56" dy="56"/>
        <cell rect="1,1064,49,59" name="arms_bg/feral_human" dx="56" dy="56"/>
        <cell rect="51,1064,49,59" name="arms_overlay_bg/feral_fur" dx="56" dy="56"/>
        <cell rect="101,1064,49,59" name="arms_overlay_bg/feral_scales" dx="56" dy="56"/>
		<cell rect="101,1064,49,59" name="arms_overlay_bg/feral_dscales" dx="56" dy="56"/>
        <cell rect="151,1064,49,59" name="arms_overlay_bg/feral_pscales" dx="56" dy="56"/>
        <cell rect="201,1064,49,59" name="arms_overlay_bg/feral_chitin" dx="56" dy="56"/>
        <cell rect="251,1064,49,59" name="arms_overlay_bg/feral_orca" dx="56" dy="56"/>
        <cell rect="351,1064,49,59" name="arms_bg/feral_dragon" dx="56" dy="56"/>
        <cell rect="451,150,49,59" name="arms_bg_pattern/Bstripe" dx="56" dy="64"/>
        <cell rect="501,150,49,59" name="arms_bg_pattern/Blightning" dx="56" dy="64"/>
        <cell rect="601,150,49,59" name="arms_bg_pattern/Btatoo" dx="56" dy="64"/>
        <cell rect="951,150,49,59" name="arms_bg_pattern/Bvenom" dx="56" dy="64"/>
        <cell rect="1,1364,49,59" name="arms_bg/gazer" dx="65" dy="65"/>
        <cell rect="1,210,49,59" name="arms/human" dx="104" dy="64"/>
        <cell rect="51,210,49,59" name="arms/fur" dx="104" dy="64"/>
        <cell rect="551,210,49,59" name="arms/furracoon" dx="104" dy="64"/>
        <cell rect="101,210,49,59" name="arms/chitin" dx="104" dy="64"/>
        <cell rect="151,210,49,59" name="arms/bee" dx="104" dy="64"/>
        <cell rect="201,210,49,59" name="arms/chitin2" dx="104" dy="64"/>
        <cell rect="251,210,49,59" name="arms/orca" dx="104" dy="64"/>
        <cell rect="301,210,49,59" name="arms/pscales" dx="104" dy="64"/>
        <cell rect="351,210,49,59" name="arms/scales" dx="104" dy="64"/>
		<cell rect="351,210,49,59" name="arms/dscales" dx="104" dy="64"/>
        <cell rect="1151,210,49,59" name="arms/shark" dx="104" dy="64"/>
        <cell rect="401,210,49,59" name="arms/goo" dx="104" dy="64"/>
        <cell rect="701,210,49,59" name="arms/panda" dx="104" dy="64"/>
        <cell rect="638,520,90,90" name="arms/yeti" dx="57" dy="43"/>
        <cell rect="1,702,90,90" name="arms/manticore_sit" dx="60" dy="61"/>
        <cell rect="92,702,90,90" name="arms/manticore_sit_fur" dx="60" dy="61"/>
        <cell rect="183,702,90,90" name="arms/manticore_sit_scales" dx="60" dy="61"/>
        <cell rect="274,702,90,90" name="arms/manticore_sit_pscales" dx="60" dy="61"/>
        <cell rect="365,702,90,90" name="arms/manticore_sit_chitin" dx="60" dy="61"/>
        <cell rect="456,702,90,90" name="arms/manticore_sit_orca" dx="60" dy="61"/>
        <cell rect="547,702,90,90" name="arms/gargoyle_sit" dx="60" dy="61"/>
        <cell rect="1,913,49,59" name="arms/displacerquad_human" dx="101" dy="56"/>
        <cell rect="51,913,49,59" name="arms/displacerquad_fur" dx="101" dy="56"/>
        <cell rect="101,913,49,59" name="arms/displacerquad_scales" dx="101" dy="56"/>
        <cell rect="151,913,49,59" name="arms/displacerquad_pscales" dx="101" dy="56"/>
        <cell rect="201,913,49,59" name="arms/displacerquad_chitin" dx="101" dy="56"/>
        <cell rect="251,913,49,59" name="arms/displacerquad_orca" dx="101" dy="56"/>
        <cell rect="1,1124,49,59" name="arms/feral_human" dx="101" dy="56"/>
        <cell rect="51,1124,49,59" name="arms_overlay/feral_fur" dx="101" dy="56"/>
        <cell rect="101,1124,49,59" name="arms_overlay/feral_scales" dx="101" dy="56"/>
        <cell rect="151,1124,49,59" name="arms_overlay/feral_pscales" dx="101" dy="56"/>
        <cell rect="201,1124,49,59" name="arms_overlay/feral_chitin" dx="101" dy="56"/>
        <cell rect="251,1124,49,59" name="arms_overlay/feral_orca" dx="101" dy="56"/>
        <cell rect="351,1124,49,59" name="arms/feral_dragon" dx="101" dy="56"/>
        <cell rect="801,210,49,59" name="arms/demonlewd" dx="100" dy="53"/>
        <cell rect="1,1184,99,119" name="arms/hinezumistanced_human" dx="58" dy="55"/>
        <cell rect="101,1184,99,119" name="arms/hinezumistanced_fur" dx="58" dy="55"/>
        <cell rect="201,1184,99,119" name="arms/hinezumistanced_scales" dx="58" dy="55"/>
        <cell rect="301,1184,99,119" name="arms/hinezumistanced_pscales" dx="58" dy="55"/>
        <cell rect="401,1184,99,119" name="arms/hinezumistanced_chitin" dx="58" dy="55"/>
        <cell rect="501,1184,99,119" name="arms/hinezumistanced_orca" dx="58" dy="55"/>
        <cell rect="601,210,49,59" name="arms/crabStance" dx="78" dy="64"/>
        <cell rect="820,520,90,90" name="arms/elemental" dx="60" dy="46"/>
        <cell rect="51,1364,49,59" name="arms/gazer" dx="92" dy="65"/>
        <cell rect="851,210,49,59" name="arms_fg/demonlewd" dx="100" dy="53"/>
        <cell rect="638,702,90,90" name="arms_fg/manticore_sit" dx="60" dy="61"/>
        <cell rect="451,210,49,59" name="arms_pattern/Bstripe" dx="104" dy="64"/>
        <cell rect="501,210,49,59" name="arms_pattern/Blightning" dx="104" dy="64"/>
        <cell rect="651,210,49,59" name="arms_pattern/Btatoo" dx="104" dy="64"/>
        <cell rect="1001,150,49,59" name="arms_pattern/undine" dx="59" dy="35"/>
        <cell rect="1001,210,49,59" name="arms_pattern/Bvenom" dx="104" dy="64"/>
        <cell rect="1,270,49,59" name="hands_bg/fur" dx="56" dy="64"/>
        <cell rect="601,270,49,59" name="hands_bg/furracoon" dx="56" dy="64"/>
        <cell rect="51,270,49,59" name="hands_bg/devil" dx="56" dy="64"/>
        <cell rect="101,270,49,59" name="hands_bg/harpy" dx="56" dy="64"/>
        <cell rect="151,270,49,59" name="hands_bg/kraken" dx="56" dy="64"/>
        <cell rect="201,270,49,59" name="hands_bg/alraune" dx="56" dy="64"/>
        <cell rect="251,270,49,59" name="hands_bg/chitin" dx="56" dy="64"/>
        <cell rect="301,270,49,59" name="hands_bg/chitin2" dx="56" dy="64"/>
		<cell rect="951,270,49,59" name="hands_bg/beeglove" dx="56" dy="64"/>
        <cell rect="351,270,49,59" name="hands_bg/fire" dx="56" dy="64"/>
        <cell rect="401,270,49,59" name="hands_bg/scales" dx="56" dy="64"/>
		<cell rect="401,270,49,59" name="hands_bg/dscales" dx="56" dy="64"/>
        <cell rect="451,270,49,59" name="hands_bg/human" dx="56" dy="64"/>
        <cell rect="501,270,49,59" name="hands_bg/fins-orca" dx="56" dy="64"/>
        <cell rect="551,270,49,59" name="hands_bg/goo" dx="56" dy="64"/>
        <cell rect="701,270,49,59" name="hands_bg/panda" dx="56" dy="64"/>
        <cell rect="301,1064,49,59" name="hand_bg/kumiho" dx="56" dy="56"/>
        <cell rect="851,150,49,59" name="hands_bg/wraithleft" dx="63" dy="75"/>
        <cell rect="651,270,49,59" name="hands_bg/frostWyrmleft" dx="62" dy="72"/>
		<cell rect="1001,270,49,59" name="hands_bg/jabberwockyleft" dx="62" dy="72"/>
        <cell rect="801,270,49,59" name="hands_bg/blade-kamaitachiMantis" dx="56" dy="64"/>
        <cell rect="751,270,49,59" name="hands_bg/wendigo" dx="56" dy="64"/>
        <cell rect="901,270,49,59" name="hands_bg/mindbreaker" dx="61" dy="74"/>
        <cell rect="351,270,49,59" name="overhands_bg/fire" dx="56" dy="64"/>
        <cell rect="1,330,49,59" name="hands/fur" dx="104" dy="64"/>
        <cell rect="601,330,49,59" name="hands/furracoon" dx="104" dy="64"/>
        <cell rect="51,330,49,59" name="hands/devil" dx="104" dy="64"/>
        <cell rect="101,330,49,59" name="hands/harpy" dx="104" dy="64"/>
        <cell rect="151,330,49,59" name="hands/kraken" dx="104" dy="64"/>
        <cell rect="201,330,49,59" name="hands/alraune" dx="104" dy="64"/>
        <cell rect="251,330,49,59" name="hands/chitin" dx="104" dy="64"/>
        <cell rect="301,330,49,59" name="hands/chitin2" dx="104" dy="64"/>
		<cell rect="951,330,49,59" name="hands/beeglove" dx="104" dy="64"/>
        <cell rect="401,330,49,59" name="hands/scales" dx="104" dy="64"/>
		<cell rect="401,330,49,59" name="hands/dscales" dx="104" dy="64"/>
        <cell rect="451,330,49,59" name="hands/human" dx="104" dy="64"/>
        <cell rect="501,330,49,59" name="hands/fins-orca" dx="104" dy="64"/>
        <cell rect="551,330,49,59" name="hands/goo" dx="104" dy="64"/>
        <cell rect="701,330,49,59" name="hands/panda" dx="104" dy="64"/>
        <cell rect="729,520,90,90" name="hands/yeti" dx="57" dy="43"/>
        <cell rect="301,1124,49,59" name="hands/kumiho" dx="101" dy="56"/>
        <cell rect="901,210,49,59" name="hands/wraithright" dx="94" dy="75"/>
        <cell rect="651,330,49,59" name="hands/frostWyrmright" dx="98" dy="72"/>
		<cell rect="1001,330,49,59" name="hands/jabberwockyright" dx="98" dy="72"/>
        <cell rect="801,330,49,59" name="hands/blade-kamaitachiMantis" dx="104" dy="64"/>
        <cell rect="751,330,49,59" name="hands/wendigo" dx="104" dy="64"/>
        <cell rect="1051,150,49,59" name="hands/gnomeLeft" dx="63" dy="42"/>
        <cell rect="1051,210,49,59" name="hands/gnomeRight" dx="60" dy="46"/>
        <cell rect="901,330,49,59" name="hands/mindbreaker" dx="97" dy="74"/>
        <cell rect="951,210,49,59" name="hands_fg/wraithrightlewd" dx="105" dy="48"/>
        <cell rect="351,330,49,59" name="overhands/fire" dx="104" dy="64"/>
        <cell rect="851,270,49,59" name="overhands/ratatoskrLeft" dx="56" dy="64"/>
        <cell rect="851,330,49,59" name="overhands/ratatoskrRight" dx="104" dy="64"/>
        <cell rect="1,390,49,59" name="legs/human" dx="79" dy="115"/>
        <cell rect="51,390,49,59" name="legs/fur" dx="79" dy="115"/>
        <cell rect="101,390,49,59" name="legs/chitin" dx="79" dy="115"/>
        <cell rect="151,390,49,59" name="legs/chitin2" dx="79" dy="115"/>
        <cell rect="201,390,49,59" name="legs/orca" dx="79" dy="115"/>
        <cell rect="251,390,49,59" name="legs/pscales" dx="79" dy="115"/>
        <cell rect="301,390,49,59" name="legs/scales" dx="79" dy="115"/>
		<cell rect="301,390,49,59" name="legs/dscales" dx="79" dy="115"/>
        <cell rect="851,390,49,59" name="legs/shark" dx="79" dy="115"/>
        <cell rect="351,390,49,59" name="legs/hoof_human" dx="79" dy="115"/>
        <cell rect="1,793,49,59" name="legs/hoof_fur" dx="79" dy="115"/>
        <cell rect="51,793,49,59" name="legs/hoof_scales" dx="79" dy="115"/>
		<cell rect="51,793,49,59" name="legs/hoof_dscales" dx="79" dy="115"/>
        <cell rect="101,793,49,59" name="legs/hoof_pscales" dx="79" dy="115"/>
        <cell rect="151,793,49,59" name="legs/hoof_chitin" dx="79" dy="115"/>
        <cell rect="201,793,49,59" name="legs/hoof_orca" dx="79" dy="115"/>
        <cell rect="251,793,49,59" name="legs/wendigo" dx="79" dy="115"/>
        <cell rect="1,520,90,90" name="legs/harpy_human" dx="60" dy="99"/>
        <cell rect="92,520,90,90" name="legs/harpy_fur" dx="60" dy="99"/>
        <cell rect="183,520,90,90" name="legs/harpy_scales" dx="60" dy="99"/>
		<cell rect="183,520,90,90" name="legs/harpy_dscales" dx="60" dy="99"/>
        <cell rect="274,520,90,90" name="legs/harpy_pscales" dx="60" dy="99"/>
        <cell rect="365,520,90,90" name="legs/harpy_chitin" dx="60" dy="99"/>
        <cell rect="456,520,90,90" name="legs/harpy_orca" dx="60" dy="99"/>
        <cell rect="547,520,90,90" name="legs/demonlewd" dx="60" dy="99"/>
        <cell rect="1,973,90,90" name="legs/displacer_human" dx="62" dy="68"/>
        <cell rect="92,973,90,90" name="legs/displacer_fur" dx="62" dy="68"/>
        <cell rect="183,973,90,90" name="legs/displacer_scales" dx="62" dy="68"/>
		<cell rect="183,973,90,90" name="legs/displacer_dscales" dx="62" dy="68"/>
        <cell rect="274,973,90,90" name="legs/displacer_pscales" dx="62" dy="68"/>
        <cell rect="365,973,90,90" name="legs/displacer_chitin" dx="62" dy="68"/>
        <cell rect="456,973,90,90" name="legs/displacer_orca" dx="62" dy="68"/>
        <cell rect="638,973,90,90" name="legs/dragon" dx="46" dy="101"/>
        <cell rect="401,390,49,59" name="legs/goo" dx="79" dy="115"/>
        <cell rect="551,390,49,59" name="legs/furracoon" dx="79" dy="115"/>
        <cell rect="651,390,49,59" name="legs/panda" dx="79" dy="115"/>
        <cell rect="1,611,90,90" name="legs/manticore_sit" dx="60" dy="61"/>